### ISSUE TITLE
Question: Dashboard apparently incomplete and no data in widgets

### ISSUE THREAD

**Issue by sgofferj** [minio/console#787]
I have started to learn minio and minio-console in my homelab. Minio itself is running on a Raspberry Pi 3 for the moment, while console is running on an Intel machine. Both are running in docker CE. Console can talk to minio and shows buckets, files, etc. I can administer things, create users, etc. Everything seems to work so far.
Just the dashboard is incomplete compared to other screenshots and the widgets show no data.

![Screenshot_20210604_120310](https://user-images.githubusercontent.com/3258466/120777395-e7515780-c52d-11eb-8b1d-9b17582bacf3.png)

I double checked the policies and they seem correct.  My user has the consoleAdmin policy attached:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

I don't see any errors in either log. Some pointers for debugging would be very much appreciated.

**Comment by harshavardhana** [comment]
> I have started to learn minio and minio-console in my homelab. Minio itself is running on a Raspberry Pi 3 for the moment, while console is running on an Intel machine. Both are running in docker CE. Console can talk to minio and shows buckets, files, etc. I can administer things, create users, etc. Everything seems to work so far.

is MinIO running on single drive? @sgofferj

**Comment by MorphBonehunter** [comment]
@sgofferj i think this is caused by https://github.com/minio/minio/issues/12430.
As this was fixed by @harshavardhana this should work in the next minio release.

**Comment by harshavardhana** [comment]
Yeah that's why I asked - Thanks for bringing that up @MorphBonehunter

**Comment by sgofferj** [comment]
@harshavardhana Affirmative. I haven't looked into erasure code yet - first wanted to get a hang of the principles.

**Comment by harshavardhana** [comment]
> @harshavardhana Affirmative. I haven't looked into erasure code yet - first wanted to get a hang of the principles.

Okay so this is fixed on server side this is not Console issue.

**Comment by carlo94it** [comment]
I've updated to latest released MinIO server version, but the problem was not solved.

![image](https://user-images.githubusercontent.com/218516/121173124-b9835000-c858-11eb-8f32-dc14dc1e3f56.png)

**Comment by userguy** [comment]
Same Issue , I have Upgraded minio server and console to latest but still not able to see updated dashboard . 

This is POC version

uname -a : 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
mc client version -  RELEASE.2021-06-08T01-29-37Z
minio version RELEASE.2021-06-07T21-40-51Z
console version 0.7.4 - 16647b88

●  server1:443
   Uptime: 16 seconds
   Version: 2021-06-07T21:40:51Z
   Network: 3/3 OK
   Drives: 6/6 OK

●  server2:443
   Uptime: 16 seconds
   Version: 2021-06-07T21:40:51Z
   Network: 3/3 OK
   Drives: 6/6 OK

●  server3:443
   Uptime: 15 seconds
   Version: 2021-06-07T21:40:51Z
   Network: 3/3 OK
   Drives: 6/6 OK

![image](https://user-images.githubusercontent.com/11783537/121219309-2faba500-c8a1-11eb-943c-b15414dcda54.png)

**Comment by harshavardhana** [comment]
> Same Issue , I have Upgraded minio server and console to latest but still not able to see updated dashboard .
> 
> This is POC version
> 
> uname -a : 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> mc client version - RELEASE.2021-06-08T01-29-37Z
> minio version RELEASE.2021-06-07T21-40-51Z
> console version 0.7.4 - [16647b8](https://github.com/minio/console/commit/16647b88e93bfa9375ccd14bc5f1b29ff501a4cf)
> 
> ● server1:443
> Uptime: 16 seconds
> Version: 2021-06-07T21:40:51Z
> Network: 3/3 OK
> Drives: 6/6 OK
> 
> ● server2:443
> Uptime: 16 seconds
> Version: 2021-06-07T21:40:51Z
> Network: 3/3 OK
> Drives: 6/6 OK
> 
> ● server3:443
> Uptime: 15 seconds
> Version: 2021-06-07T21:40:51Z
> Network: 3/3 OK
> Drives: 6/6 OK
> 
> ![image](https://user-images.githubusercontent.com/11783537/121219309-2faba500-c8a1-11eb-943c-b15414dcda54.png)

The dashboard is already visible - if you need prometheus like UI you need to configure prometheus and then configure console to talk to prometheus with 

CONSOLE_PROMETHEUS_URL

**Comment by sgofferj** [comment]
Just for clarity: Minio Console only provides the 3 widgets seen above? Everything else which can be seen in other dashboards screenshots requires prometheus?

**Comment by harshavardhana** [comment]
> Just for clarity: Minio Console only provides the 3 widgets seen above? Everything else which can be seen in other dashboards screenshots requires prometheus?

Yes @sgofferj

**Comment by userguy** [comment]
I have configured Prometheus as per documentation . I can also see metrics in grafana .
Do we have it in documentation how to add metrics in console dashboard . 


![image](https://user-images.githubusercontent.com/11783537/121230241-a39f7a80-c8ac-11eb-822f-d26334b2662b.png)



global:  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.  # scrape_timeout is set to the global default (10s).
# A scrape configuration containing exactly one endpoint to scrape:# Here it's Prometheus itself.scrape_configs:    # The job name is added as a label `job=&lt;job_name&gt;` to any timeseries scraped from this config.  - job_name: minio-node1    metrics_path: /minio/v2/metrics/cluster    scheme: http    static_configs:    - targets:       - 'localhost:9000'

**Comment by harshavardhana** [comment]
> Do we have it in documentation how to add metrics in console dashboard .

@userguy I mentioned `CONSOLE_PROMETHEUS_URL=http://prometheus_url:port`

**Comment by userguy** [comment]
@harshavardhana  Thanks . It works . So for if above line can be added in this section this will help to enable the dashboard for all users who want to see new console. 

So if someone is upgrading please ensure you update api endpoint for v2 in prometheus.yml

"before running console service, following environment settings must be supplied"
